apiVersion: v1
kind: Service
metadata:
    name: batchgeocode
    namespace: default
    labels:
        app: batchgeocode
spec:
    type: ClusterIP
    ports:
        - name: batchgeocode
          port: 80
          protocol: TCP
          targetPort: 5000
    selector:
        app: batchgeocode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    namespace: default
    name: batchgeocode
spec:
    selector:
        matchLabels:
            app: batchgeocode
    serviceName: batchgeocode
    replicas: 1
    template:
        metadata:
            labels:
                app: batchgeocode
        spec:
            dnsPolicy: Default
            containers:
              - name: batchgeocode
                image: mlc314/batch_geocode
                ports:
                  - name: batchgeocode
                    containerPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: batchgeocode
    namespace: default
spec:
    entryPoints:
        - ssl
    routes:
    # NOTE: backticks - NOT QUOTES
    - match: Host(`batch-geocode.sae.ihme.washington.edu`)
      kind: Rule
      services:
      - name: batchgeocode
        port: 80
    tls:
        store:
            name: default