name: geocoding
channels:
  - defaults
dependencies:
  - openssl=1.0.2l
  - pip=9.0.1
  - python=3.6.2
  - setuptools=36.4.0
  - sqlite=3.13.0
  - tk=8.5.18
  - wheel=0.29.0
  - xz=5.2.3
  - zlib=1.2.11
  - pip:
    - backcall==0.1.0
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.0
    - decorator==4.3.0
    - flask==1.0.2
    - idna==2.7
    - ipython==7.1.1
    - ipython-genutils==0.2.0
    - itsdangerous==1.1.0
    - jedi==0.13.1
    - jinja2==2.10
    - markupsafe==1.1.0
    - numpy==1.15.4
    - pandas==0.23.4
    - parso==0.3.1
    - pickleshare==0.7.5
    - prompt-toolkit==2.0.7
    - pygments==2.2.0
    - python-dateutil==2.7.5
    - pytz==2018.7
    - requests==2.20.1
    - six==1.11.0
    - traitlets==4.3.2
    - urllib3==1.24.1
    - wcwidth==0.1.7
    - werkzeug==0.14.1