name: geocoding
channels:
- defaults
dependencies:
- certifi=2016.2.28
- openssl=1.0.2l
- pip=9.0.1
- python=3.6.2
- setuptools=36.4.0
- sqlite=3.13.0
- tk=8.5.18
- wheel=0.29.0
- xz=5.2.3
- zlib=1.2.11
- pip:
  - click==7.0
  - flask==1.0.2
  - itsdangerous==1.1.0
  - jinja2==2.10
  - markupsafe==1.1.0
  - werkzeug==0.14.1
